import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import Link from 'next/link';
import { useState } from 'react';
import InputAdornment from '@mui/material/InputAdornment';
import IconButton from '@mui/material/IconButton';
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';
import { useForm } from "react-hook-form";
import { yupResolver } from '@hookform/resolvers/yup';
import * as Yup from 'yup';
import { fetchApi } from '../helper/api';
import { IsAlert } from '../component/IsAlert';
import { useRouter } from 'next/router';



export default function Register() {
  const router = useRouter()
  const [values, setValues] = useState({
    showPassword: false,
    showConsfirmPassword: false,
  });
  const validationSchema = Yup.object().shape({
    name: Yup.string().required('Name required'),
    email: Yup.string().required('Email required').email("Invalid email"),
    password: Yup.string().required('Password required'),
    confirm_password: Yup.string().required('Password required').oneOf([Yup.ref('password')], 'Passwords does not match'),
  });
  const formOptions = { resolver: yupResolver(validationSchema) };
  const { register, handleSubmit, formState: { errors } } = useForm(formOptions);
  const onSubmit = async (data) => {
    var res = await fetchApi("signup", "POST", false, data)
    if (res.status == 200) {
      IsAlert.fire({
        title: "",
        text: res.data.response.message,
        icon: "success",
        showCancelButton: false,
        focusConfirm: false,
        confirmButtonText: 'OK',
  
      }).then(async function (isConfirm) {
        if (isConfirm.isConfirmed) {
          router.push('/')
        }
      })
    }
    else{
      IsAlert.fire({
        title: "",
        text: res.data.response.message,
        icon: "error",
        showCancelButton: false,
        focusConfirm: false,
        confirmButtonText: 'OK',
  
      }).then(async function (isConfirm) {
        if (isConfirm.isConfirmed) {
          
        }
      })
    }
  }
  return (
    <>
      <Head>
        <title>Register - Pensieve</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/pensieve.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <form onSubmit={handleSubmit(onSubmit)} style={{ flex: 1 }}>
          <Box sx={{ flexGrow: 1 }} style={{ width: "25vw" }} >
            <Grid container spacing={2}>
              <Grid item xs={12}>
                <TextField
                  variant="filled"
                  fullWidth={true}
                  label="Name"
                  {...register("name")}
                  helperText={errors.name ? errors.name.message : ""}
                  error={errors.name ? true : false}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  variant="filled"
                  fullWidth={true}
                  label="Email"
                  {...register("email")}
                  helperText={errors.email ? errors.email.message : ""}
                  error={errors.email ? true : false}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  variant="filled"
                  fullWidth={true}
                  label="Password"
                  type={values.showPassword ? 'text' : 'password'}
                  {...register("password")}
                  helperText={errors.password ? errors.password.message : ""}
                  error={errors.password ? true : false}
                  InputProps={{
                    endAdornment: <InputAdornment position="end">
                      <IconButton
                        aria-label="toggle password visibility"
                        onClick={() => {
                          setValues({
                            ...values,
                            showPassword: !values.showPassword
                          })
                        }}
                        edge="end"
                      >
                        {values.showPassword ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>,
                  }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  variant="filled"
                  fullWidth={true}
                  label="Confirm Password"
                  type={values.showConsfirmPassword ? 'text' : 'password'}
                  {...register("confirm_password")}
                  helperText={errors.confirm_password ? errors.confirm_password.message : ""}
                  error={errors.confirm_password ? true : false}
                  InputProps={{
                    endAdornment: <InputAdornment position="end">
                      <IconButton
                        aria-label="toggle password visibility"
                        onClick={() => {
                          setValues({
                            ...values,
                            showConsfirmPassword: !values.showConsfirmPassword
                          })
                        }}
                        edge="end"
                      >
                        {values.showConsfirmPassword ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>,
                  }}
                />
              </Grid>
            </Grid>
            <Grid
              container
              direction="row"
              justifyContent="center"
              alignItems="center"
              style={{ marginTop: '20px' }}
            >
              <Grid item xs={3}>
                <Button type='submit' className={styles.thirteen} fullWidth={true} variant="outlined">Register</Button>
              </Grid>
            </Grid>
            <Grid
              container
              direction="row"
              justifyContent="center"
              alignItems="center"
              style={{ marginTop: '20px' }}
            >
              <Link href="/">
                Have Account?
              </Link>
            </Grid>
          </Box>
        </form>
      </main>
    </>
  )
}
